### ISSUE TITLE
启动es和安装插件 出错，我使用5.5.0

### ISSUE THREAD

**Issue by hubiao1** [hualongdata/hanlp-ext#6]
(Bootstrap.java:351) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.0.jar:5.5.0]
	... 6 more
Caused by: java.lang.IllegalStateException: jar hell!
class: org.apache.logging.log4j.CloseableThreadContext$Instance
jar1: D:\java\elasticsearch-5.5.0\plugins\elasticsearch-hanlp\log4j-api-2.8.2.jar
jar2: D:\java\elasticsearch-5.5.0\lib\log4j-api-2.8.2.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:282) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:192) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:374) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:140) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.node.Node.<init>(Node.java:312) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.0.jar:5.5.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.0.jar:5.5.0]
	... 6 more

**Comment by niko-liu** [comment]
https://github.com/niko-liu/hanlp-ext
试试我这边的分支
